[package]
name = "tendec"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.16.1"
ndarray-rand = "0.15"
ndarray-linalg = { version = "0.17.0", features = ["openblas"] }
rand = "0.9.1"
approx = "0.5.1"
rayon = "1.10.0"